import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header'
import Footer from "./components/Footer";

import { connectToMongoDB } from "./lib/db";

import ThemeProviderWrapper from "./ThemeProviderWrapper";
import StoreProvider from "./StoreProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const layout = async ({ children }: Readonly<{ children: React.ReactNode }>) => {

  connectToMongoDB()

  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ThemeProviderWrapper>
            <Header />
            {children}
            <Footer />
          </ThemeProviderWrapper>
        </StoreProvider>
      </body>
    </html>
  )
}

export default layout